'use client';
import { Geist, Geist_Mono, Protest_Guerrilla } from "next/font/google";
import "@/app/globals.css";
import Link from "next/link";
import { Metadata } from "next";
import { useState } from "react";

const protestGuerrilla = Protest_Guerrilla({
  variable: "--font-protest-guerrilla",
  weight: "400",
  subsets: ["latin"]
});


// export const metadata: Metadata = {
//   title: "Auth Layout",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [inputValue, setInputValue] = useState('');

  return (
    <>
      
        <Link href='/' className="fixed bg-gray-600 m-2 p-2 text-4xl rounded-[10px]">
            Home 🔙
        </Link>
      
      <div
        className={`${protestGuerrilla.variable} antialiased flex flex-col items-center justify-center bg-blue-900 h-screen`}
      >
        <p className="text-4xl underline">Authentication</p>
        <input 
          value={inputValue}
          type="text" 
          placeholder="Enter text" 
          onChange={(e)=>{
            let text = e.target.value;
            setInputValue(text);
          }}
          className="border-2 text-3xl p-1.5 rounded-[8px]" 
        />

        {children}

        <div className="bg-amber-600 flex gap-5 p-2 mt-3">
          <Link href="/login" className="text-3xl bg-pink-600 p-2">Login</Link>
          <Link href="/register" className="text-3xl bg-pink-600 p-2">Register</Link>
          <Link href="/forget-password" className="text-3xl bg-pink-600 p-2">Forgot Password</Link>
        </div>

      </div>
    </>
  );
}